# Generated by Django 4.0.2 on 2022-06-21 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoForm',
            fields=[
                ('nombre', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Nombre')),
                ('email', models.CharField(max_length=20, verbose_name='Email')),
                ('mensaje', models.CharField(max_length=20, verbose_name='Mensaje')),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_producto',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Id producto'),
        ),
    ]
