# Generated by Django 4.0.2 on 2022-06-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='nombre_categoria',
            field=models.CharField(max_length=20, null=True, verbose_name='Categoria'),
        ),
    ]
